advertised_listener="127.0.0.1:8090" #Optional ip and port that http proxy bind on (default: 0.0.0.0:8080)
debug_port=":6060"                   #Optional debugging port (default: 6060)

[log]
format="json"           #text,json (default: text)
log_level="debug"       #Optiona debug,info,warning,error (default: warning)
log_point="/directory/path/to/store/logs" #Optional (default: stdout)

[kafka-producer]
zookeeper="127.0.0.1:2181/kafka"
zookeeper_timeout=5             #Second
max_retries=10                  #Optional (default: 10)
producer_registration_namespace="/kafka-rest-proxy" #Optional (default: /kafka-rest-proxy)